# Generated by Django 2.2 on 2022-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0003_auto_20220601_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.TextField(max_length=115),
        ),
    ]
